### ISSUE TITLE
Should function prefix be fbg_ or fb_?

### ISSUE THREAD

**Issue by Rekyt** [FRBCesab/funbiogeo#1]
We stated in our [Design Principles](https://github.com/FRBCesab/funbiogeo/wiki/Design-principles) that we will prefix all the functions by `fbg_`  but I have the feeling that a three-letters prefix is going to be more cumbersome than a two-letters prefix like `fb_`.

This is a very minor issue but I wanted to make a note somewhere about it.

**Comment by ahasverus** [comment]
Agreed to use `fb_`.
