### ISSUE TITLE
What should default argument order be?

### ISSUE THREAD

**Issue by Rekyt** [FRBCesab/funbiogeo#2]
For the moment the package expects site-species matrix first then traits matrix.
What should the order be to be consistent with other packages?

Like funrar, fundiversity, ade4, FD, mFD, etc.

**Comment by ahasverus** [comment]
Do you mean during the first checks of functions? I think checking `sites x species` matrix first is good.

**Comment by Rekyt** [comment]
> Do you mean during the first checks of functions? I think checking `sites x species` matrix first is good.

I mean for all the functions in `funbiogeo`. Do we want the first argument to be the site x species matrix? like in `funrar`, `fundiversity`, `vegan`.
Or the species x traits matrix like in `FD` and `adiv` for example.

The convention is not super clear here and I just want to avoid confusion for the user.
For me site x species is fine, but I wanted to make sure we think about this issue early when making the package.

**Comment by Rekyt** [comment]
it seems we do site_species, species_traits, and then the rest. Closing now but will revisit if we need to formalize this more.
