### ISSUE TITLE
Weird character in fb_plot_trait_combination_frequencies()

### ISSUE THREAD

**Issue by Rekyt** [FRBCesab/funbiogeo#64]
The y-axis labels have a weird character before the proportion.

See example:

![image](https://user-images.githubusercontent.com/5593751/176862907-5a17148e-3aca-4eee-943c-9980cd58df04.png)

**Comment by ahasverus** [comment]
I think this bug come from the use of `\t`. Maybe just separate the number and the pourcentage by a single ` `?
