### ISSUE TITLE
Remove color of edges of polygonal sites on maps because unreadable

### ISSUE THREAD

**Issue by Rekyt** [FRBCesab/funbiogeo#65]
If we look at `fb_map_site_traits_completeness()` (https://frbcesab.github.io/funbiogeo/reference/fb_map_site_traits_completeness.html)

![image](https://user-images.githubusercontent.com/5593751/176864270-4d9844ba-1243-4e68-8f3f-d70d12429cac.png)

The edges of the polygonal sites are dark grey which makes them hard to read when in small. Best would be by default to remove them.

**Comment by ahasverus** [comment]
I agree!
