### ISSUE TITLE
Be explicit when computing coverage using all traits

### ISSUE THREAD

**Issue by Rekyt** [FRBCesab/funbiogeo#66]
Several function compute trait coverage across all traits taken together. (like https://frbcesab.github.io/funbiogeo/reference/fb_map_site_traits_completeness.html)

This should be explicit from a documentation point of view. And maybe should be optional?

**Comment by ahasverus** [comment]
I think it can be optional.
But I would use instead the argument `by_trait = TRUE` to compute coverage at the trait level. If this argument is `FALSE`, then only the coverage over all traits is computed.

**Comment by Rekyt** [comment]
Concerned functions:

- `fb_get_all_trait_coverages_by_site()`
- `fb_map_site_traits_completeness()`
- `fb_plot_distribution_site_trait_coverage()`
- `fb_plot_site_traits_completeness()`
- `fb_plot_species_traits_completeness()`

**Comment by Rekyt** [comment]
For all these functions we could instead have an argument `all_traits = TRUE/FALSE` to control the behavior of considering all traits together. By default, `all_traits = TRUE`.
